/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.romaneio.views;

import br.romaneio.core.entity.ContadorDias;
import br.romaneio.core.entity.Dia;
import br.romaneio.core.entity.dao.CarregarTabelas;
import br.romaneio.core.entity.dao.HistoricoMesDAO;
import java.text.DecimalFormat;
import javax.swing.DefaultListModel;

/**
 *
 * @author valdemar
 */
public class Historico extends javax.swing.JFrame {

    /**
     * Creates new form Historico
     */
    public Historico() {
        initComponents();
        limparJL();
        carregartables();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        exibirMes = new javax.swing.JList<>();
        botaoCarregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        diaAte15 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        litros01 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        litros02 = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        diaAte31 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        campoLitrosTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        valoRecebido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        exibirMes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(exibirMes);

        botaoCarregar.setText("Carregar");
        botaoCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCarregarActionPerformed(evt);
            }
        });

        diaAte15.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(diaAte15);

        litros01.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(litros01);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Dia");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Litros");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Dia");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Litros");

        litros02.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(litros02);

        diaAte31.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(diaAte31);

        jLabel5.setText("Litros total :");

        jLabel6.setText("valor-recebido");

        valoRecebido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valoRecebidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoLitrosTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valoRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel4)))
                                .addGap(67, 67, 67))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botaoCarregar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(botaoCarregar)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoLitrosTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(valoRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCarregarActionPerformed
        // Botão carregar
        limparLitros();
        limparLitros02();
        carregarTotalDias();
        if(select() != null){
            carregarLitros();
            carregarLitros02();
        }else{}
        //select();
        
        
    }//GEN-LAST:event_botaoCarregarActionPerformed

    private void valoRecebidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valoRecebidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valoRecebidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Historico().setVisible(true);
                
            }
        });
    }
    
     //----------------------Fução selecionar--------------------------------------
   
    public String select(){

        //DefaultListModel modelo = (DefaultListModel) jList1.getModel();
        String valor = null;
        Object selectedItem = exibirMes.getSelectedValue();
        if (selectedItem != null) {
             valor = (String) selectedItem;
             
        }
        return valor;
    }
    
    //--------------------------Fução exbir tabelas--------------------
    
    public  void carregartables(){
    
        DefaultListModel model = (DefaultListModel) exibirMes.getModel();
        
        CarregarTabelas ctb = new CarregarTabelas();
        String [] tabelas = ctb.carregar();
        
        for(String tabela : tabelas ){
            model.addElement(tabela);
        }
        
        
    }
    
    //--------------------------Fução carregar litros --------------------
    
    public DefaultListModel carregarLitros(){
        String nome = select();
        DefaultListModel model = (DefaultListModel) litros01.getModel();
        int litrosTotal = 0;
        
        for(int i = 1; i <= 15; i++){
        
            Long id = Long.valueOf(i);
            HistoricoMesDAO dao = new HistoricoMesDAO();
            Dia dia = dao.carregar(id, nome);
            if(dia != null){
                int litros = dia.getLitros();
                Double valoLeite = dia.getValorLeite();
                model.addElement(litros);
                litrosTotal += litros;
                campoLitrosTotal.setText(String.valueOf(litrosTotal));
                Double mutilicador = Double.valueOf(litrosTotal);
                Double reais = mutilicador * valoLeite;
                valoRecebido.setText(String.valueOf(reais));
                
            }
        }
        
        return model;
    }
    
    public DefaultListModel carregarLitros02(){
        
        String nome = select();
        DefaultListModel modelo = (DefaultListModel) litros02.getModel();
        int litroGet = Integer.parseInt(campoLitrosTotal.getText());
       for(int i = 16; i <= 31; i++){
        
            Long id = Long.valueOf(i);
            HistoricoMesDAO dao = new HistoricoMesDAO();
            Dia dia = dao.carregar(id, nome);
            if(dia != null){
                
                int litros = dia.getLitros();
                Double valorLeite = dia.getValorLeite();
                Double furural = dia.getFurural();
                
                modelo.addElement(litros);
                litroGet += litros;
                campoLitrosTotal.setText(String.valueOf(litroGet));
                Double mutiplicado = Double.valueOf(litroGet);
                Double reais = mutiplicado * valorLeite;
                double descontoFurural = reais - (reais * (furural / 100.0));
                
                DecimalFormat df = new DecimalFormat("#,###.00");
                df.format(1234.36); 
                
                valoRecebido.setText(df.format(descontoFurural));
           }
        }
        return modelo;
    }
    public DefaultListModel diaAte15(){
        DefaultListModel modelo = (DefaultListModel) diaAte15.getModel();
        
        for(int i = 1; i <= 15;i++){
            
            modelo.addElement(i);
        }
        
        return modelo;
    } 
    public DefaultListModel diaAte31(){
        DefaultListModel modelo = (DefaultListModel) diaAte31.getModel();
        ContadorDias cd = new ContadorDias();
        int dia = cd.calendario();
        for(int i = 16; i <= dia ;i++){
            
            modelo.addElement(i);
        }
        
        return modelo;
    }   
    public void carregarTotalDias(){
        diaAte15();
        diaAte31();
    }
    //-----------------------Limpar Jlist----------------------------------------
   
    public DefaultListModel limparJL(){
    
        DefaultListModel limpar = new DefaultListModel();
        exibirMes.setModel(limpar);
        return limpar;
    }
    public DefaultListModel limparLitros(){
    
        DefaultListModel limpar = new DefaultListModel();
        litros01.setModel(limpar);
        limparDia15();
        return limpar;
        
    }
    public DefaultListModel limparLitros02(){
    
        DefaultListModel limpar = new DefaultListModel();
        litros02.setModel(limpar);
        return limpar;
    }
    public DefaultListModel limparDia15(){
    
        DefaultListModel limpar = new DefaultListModel();
        DefaultListModel limpar02 = new DefaultListModel();
        diaAte15.setModel(limpar);
        diaAte31.setModel(limpar02);
        return limpar;
    }
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCarregar;
    private javax.swing.JTextField campoLitrosTotal;
    private javax.swing.JList<String> diaAte15;
    private javax.swing.JList<String> diaAte31;
    private javax.swing.JList<String> exibirMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JList<String> litros01;
    private javax.swing.JList<String> litros02;
    private javax.swing.JTextField valoRecebido;
    // End of variables declaration//GEN-END:variables
}
